import test from 'node:test';
import assert from 'node:assert/strict';
import { compilePrompt, importComfy, nodeFromInfo, ports } from '../src/comfyGraph.js';
const catalog = { Source: { input: { required: { seed: ['INT', { default: 1, min: 0 }], text: ['STRING', { default: 'hello', multiline: true }] } }, output: ['LATENT'], output_name: ['latent'] }, Output: { input: { required: { latent: ['LATENT', {}] } }, output: [], output_node: true }, Custom: { input: { required: { mode: [['a', 'b'], {}] } }, output: ['IMAGE'] } };
const prompt = { '1': { class_type: 'Source', inputs: { seed: 7, text: 'flower' } }, '2': { class_type: 'Output', inputs: { latent: ['1', 0] } } };
test('Comfy API import/export preserves typed links and widget values', () => { const graph = importComfy(prompt, catalog); const restored = compilePrompt(graph, catalog); assert.deepEqual(restored['1'].inputs, prompt['1'].inputs); assert.deepEqual(restored['2'].inputs, prompt['2'].inputs); assert.equal(graph.edges[0].targetHandle, 'latent'); });
test('Dynamic custom nodes use actual metadata and enum defaults', () => { const node = nodeFromInfo('c', 'Custom', catalog.Custom, { x: 1, y: 2 }); assert.equal(node.data.widgets.mode, 'a'); assert.deepEqual(ports(catalog.Source).outputs, [{ name: '0', type: 'LATENT', label: 'latent' }]); });
test('Reject mismatched type, duplicate input and cycles', () => { const g = importComfy(prompt, catalog); const wrong = structuredClone(catalog); wrong.Source.output = ['IMAGE']; assert.throws(() => compilePrompt(g, wrong), /端口类型/); const duplicate = importComfy(prompt, catalog); duplicate.edges.push({ ...duplicate.edges[0], id: 'duplicate' }); assert.throws(() => compilePrompt(duplicate, catalog), /只能有一条/); const cycle = importComfy(prompt, catalog); cycle.edges.push({ id: 'cycle', source: '2', target: '1', sourceHandle: '0', targetHandle: 'seed' }); assert.throws(() => compilePrompt(cycle, catalog), /循环/); });
test('UI workflow mapping is strict and never silently imports an unrelated default graph', () => { const raw = { nodes: [{ id: 1, type: 'Source', pos: [10, 20], widgets_values: [7, 'flower'], inputs: [{ name: 'seed', widget: { name: 'seed' } }, { name: 'text', widget: { name: 'text' } }] }, { id: 2, type: 'Output', pos: [100, 20], widgets_values: [], inputs: [{ name: 'latent' }] }], links: [[1, 1, 0, 2, 0, 'LATENT']] }; assert.deepEqual(compilePrompt(importComfy(raw, catalog), catalog)['2'].inputs, { latent: ['1', 0] }); raw.nodes[0].widgets_values.push('randomize'); assert.throws(() => importComfy(raw, catalog), /控件顺序/); assert.throws(() => importComfy({ garbage: 123 }, catalog), /缺少节点定义/); });
