import { useEffect, useRef, useState } from 'react';
import { getKnowledgeMap,getAbilityPortrait,getToolTrail,getGrowthRecord,saveKnowledgePath,recordKnowledgeActivity,recordKnowledgeToolUsage } from './services/adminApi.js';
import {knowledgeLayout} from './knowledgeMapModel.js';
import './KnowledgeMap.css';
const views=[['map','知识地图'],['abilities','能力目标'],['tools','工具轨迹'],['growth','成长记录']];
export function KnowledgeMap({account,onNavigate,onNotice}) {
 const [data,setData]=useState(null),[view,setView]=useState('map'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[path,setPathState]=useState([]),[title,setTitle]=useState('我的学习路径'),[filter,setFilter]=useState(''),[activity,setActivity]=useState({activityType:'learn',minutes:0,note:''});
 const request=useRef(0),pathDirty=useRef(false);
 const setPath=next=>{pathDirty.current=true;setPathState(next);};
 const load=async()=>{const id=++request.current;setError('');try{const [map,abilities,tools,growth]=await Promise.all([getKnowledgeMap(),getAbilityPortrait(),getToolTrail(),getGrowthRecord()]);if(id!==request.current)return;setData({map,abilities,tools,growth});if(!pathDirty.current){setPathState(map.path.nodeIds);setTitle(map.path.title);}}catch(e){if(id===request.current)setError(e.message);}};
 useEffect(()=>{pathDirty.current=false;setData(null);void load();return()=>{request.current++;};},[account.id]);
 const mutate=async work=>{setBusy(true);try{await work();onNotice('已保存');await load();}catch(e){onNotice(e.message);}finally{setBusy(false);}};
 if(error)return <section className="knowledge-live"><h2>知识图谱暂时无法加载</h2><p role="alert">{error}</p><button onClick={load}>重新加载</button></section>;
 if(!data)return <section className="knowledge-live" aria-busy="true">正在加载知识点与学习记录…</section>;
 const {map,abilities,tools,growth}=data;
 const filteredNodes=map.nodes.filter(n=>(n.title+n.domain).toLowerCase().includes(filter.toLowerCase()));
 const filteredIds=new Set(filteredNodes.map(n=>n.id));
 const filteredEdges=map.edges.filter(e=>filteredIds.has(e.fromNodeId)&&filteredIds.has(e.toNodeId));
 const layout=knowledgeLayout(filteredNodes,filteredEdges);
 const node=filteredNodes.find(n=>n.id===selected) ?? filteredNodes[0];
 const resources=node?map.bindings.filter(b=>b.nodeId===node.id):[];
 const go=resource=>{if(!resource.href)return;if(resource.targetType==='tool')void recordKnowledgeToolUsage(resource.targetId).catch(e=>onNotice('工具已打开，但访问记录未保存：'+e.message));try{const url=new URL(resource.href,window.location.origin);if(!['https:','http:'].includes(url.protocol))throw Error('资源地址不可用');if(url.origin===window.location.origin)onNavigate(url.pathname+url.search);else window.open(url.href,'_blank','noopener,noreferrer');}catch(e){onNotice(e.message);}};
 const move=(i,offset)=>setPath(ids=>{const next=[...ids],j=i+offset;if(j<0||j>=next.length)return ids;[next[i],next[j]]=[next[j],next[i]];return next;});
 return <section className="knowledge-live"><header><div><h2>知识图谱</h2><p>连接已发布知识点、课程与工作流，沿真实记录继续学习。</p></div><button onClick={load} disabled={busy}>刷新记录</button><button onClick={()=>onNavigate('/my-learning?atlas=reference')}>查看课程参考总览</button><button onClick={()=>onNavigate('/my-learning?atlas=personal')}>查看学习历程</button></header>
 <nav aria-label="知识图谱视图">{views.map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</nav>
 {view==='map'&&<><p>{map.summary.total} 个知识点 · {map.summary.completed} 个达到记录目标</p><label>搜索知识点<input value={filter} onChange={e=>setFilter(e.target.value)} /></label>
 {map.nodes.length>0&&<div className="knowledge-live__graph" tabIndex={0} aria-label="知识关系图，可横向滚动"><svg width={layout.width} height={layout.height} aria-label="数据库知识点与关系"><defs><marker id="knowledge-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#68856b"/></marker></defs>{filteredEdges.map(e=>{const a=layout.nodes.find(n=>n.id===e.fromNodeId),b=layout.nodes.find(n=>n.id===e.toNodeId);return a&&b?<line key={e.fromNodeId+e.toNodeId+e.relation} x1={a.x+85} y1={a.y} x2={b.x-90} y2={b.y} stroke="#68856b" strokeWidth="2" strokeDasharray={e.relation==='related'?'5 4':undefined} markerEnd={e.relation==='prerequisite'?'url(#knowledge-arrow)':undefined}><title>{a.title} → {b.title} · {e.relation==='prerequisite'?'前置':'相关'}</title></line>:null;})}{layout.nodes.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={'查看知识点 '+n.title} onClick={()=>setSelected(n.id)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();setSelected(n.id);}}}><rect x={n.x-85} y={n.y-35} width="170" height="70" rx="20" fill={node?.id===n.id?'#dceedd':'#fff'} stroke="#6b916e"/><text x={n.x} y={n.y-2} textAnchor="middle">{n.title.length>10?n.title.slice(0,10)+'…':n.title}</text><text x={n.x} y={n.y+20} textAnchor="middle" fontSize="12">{n.progressPercent}% 记录进度</text><title>{n.title}</title></g>)}</svg></div>}
 {!map.nodes.length?<p role="status">尚未发布知识点。教师可在管理台维护知识点，或为已发布课程配置知识标签。</p>:<div className="knowledge-live__layout"><div><div className="knowledge-live__nodes">{filteredNodes.map(n=><button key={n.id} className={node?.id===n.id?'selected':''} onClick={()=>setSelected(n.id)}><strong>{n.title}</strong><small>{({general:'通用',foundation:'设计基础',method:'方法与体验',visual:'视觉表达',interaction:'交互实践',material:'材料与造型'})[n.domain]??n.domain} · {n.progressPercent}% 学习记录进度</small></button>)}</div><h3>知识关联</h3>{filteredEdges.length?<ul>{filteredEdges.map(e=><li key={e.fromNodeId+e.toNodeId+e.relation}><button onClick={()=>setSelected(e.fromNodeId)}>{map.nodes.find(n=>n.id===e.fromNodeId)?.title}</button><span>{e.relation==='prerequisite'?' → 前置关系 → ':' ↔ 相关知识 ↔ '}</span><button onClick={()=>setSelected(e.toNodeId)}>{map.nodes.find(n=>n.id===e.toNodeId)?.title}</button></li>)}</ul>:<p>尚未配置知识关系，不推测前置要求。</p>}</div>
 {node&&<article><h3>{node.title}</h3><p>{node.description||'暂无知识说明'}</p><p>{node.evidenceCount} 条学习依据 · {node.progressPercent}% 记录进度</p><h4>关联学习资源</h4>{resources.length?resources.map(b=><button key={b.targetType+b.targetId} onClick={()=>go(b)}>{b.title} · {({course:'课程',lesson:'课时',workflow:'工作流',tool:'工具'})[b.targetType]}</button>):<p>暂无可访问资源，等待教师补充。</p>}<button disabled={busy||path.includes(node.id)} onClick={()=>setPath(ids=>[...ids,node.id])}>加入我的路径</button><form onSubmit={e=>{e.preventDefault();void mutate(()=>recordKnowledgeActivity({nodeId:node.id,...activity,minutes:Number(activity.minutes)}));}}><h4>记录学习活动</h4><label>活动<select value={activity.activityType} onChange={e=>setActivity({...activity,activityType:e.target.value})}><option value="learn">学习</option><option value="practice">练习</option><option value="create">创作</option></select></label><label>分钟<input type="number" min="0" max="1440" value={activity.minutes} onChange={e=>setActivity({...activity,minutes:e.target.value})} /></label><label>说明<textarea value={activity.note} maxLength={1000} onChange={e=>setActivity({...activity,note:e.target.value})} /></label><button disabled={busy}>保存活动</button></form></article>}</div>}
 <aside><h3>下一步建议</h3>{map.recommendations.length?map.recommendations.map(rec=><button key={rec.nodeId} onClick={()=>setSelected(rec.nodeId)}>{map.nodes.find(n=>n.id===rec.nodeId)?.title} · {rec.reason}</button>):<p>暂无可推荐资源，请查看知识点或联系教师补充。</p>}</aside>
 <form onSubmit={e=>{e.preventDefault();void mutate(async()=>{await saveKnowledgePath({title,nodeIds:path});pathDirty.current=false;});}}><h3>我的学习路径</h3><label>路径名称<input required maxLength={120} value={title} onChange={e=>{pathDirty.current=true;setTitle(e.target.value);}} /></label><ol>{path.map((id,i)=><li key={id}><span>{map.nodes.find(n=>n.id===id)?.title??'知识点已下架，请移除'}</span><button type="button" aria-label={'上移第'+(i+1)+'项'} disabled={i===0} onClick={()=>move(i,-1)}>上移</button><button type="button" aria-label={'下移第'+(i+1)+'项'} disabled={i===path.length-1} onClick={()=>move(i,1)}>下移</button><button type="button" onClick={()=>setPath(ids=>ids.filter(x=>x!==id))}>移除</button></li>)}</ol><p>未完成的前置知识点需要加入路径并排在后续知识点之前。</p><button disabled={busy}>保存路径</button></form></>}
 {view==='abilities'&&<><h3>能力目标关联</h3>{abilities.goals.length?abilities.goals.map(g=><article key={g.id}><h4>{g.title}</h4><p>{g.description}</p><p>{g.progressPercent}% 关联学习记录 · {g.completedNodes}/{g.totalNodes} 个知识点达到记录目标</p></article>):<p>教师尚未发布能力目标。</p>}</>}
 {view==='tools'&&<><h3>工具轨迹</h3><p>平台工作流执行与工具入口访问分别统计；访问不代表完成工具实践。</p>{tools.tools.length?tools.tools.map(t=><article key={t.id}><strong>{t.name}</strong><p>工作流 {t.runCount} 次（完成 {t.completedRunCount} 次） · 直接访问 {t.directUseCount} 次</p>{t.entryUrl&&<button onClick={()=>go({href:t.entryUrl,targetType:"tool",targetId:t.id})}>打开工具</button>}</article>):<p>暂无工具记录。</p>}</>}
 {view==='growth'&&<><h3>成长记录</h3>{growth.timeline.length?<ol>{growth.timeline.map(e=><li key={e.id}><strong>{e.title}</strong> · {({learn:"学习",practice:"练习",create:"创作",lesson:"课时完成",workflow:"工作流完成",work:"作品",upload:"资料上传",tool:"工具访问"})[e.type]??"活动"} · <time>{new Date(e.occurredAt).toLocaleString('zh-CN')}</time>{e.note&&<p>{e.note}</p>}</li>)}</ol>:<p>完成课时或记录学习活动后会显示成长足迹。</p>}</>}
 <p className="knowledge-live__note">记录进度由课程、已发布版本的工作流和自行记录活动计算，不代表教师评分或知识掌握认证。课程参考总览是规划内容，不计入学习进度。</p></section>;
}
