import {useEffect,useRef,useState} from 'react';
import {getManagedKnowledgeMap,syncKnowledgeLabels,createKnowledgeNode,updateKnowledgeNode,saveKnowledgeLinks,createAbilityGoal,updateAbilityGoal} from './services/adminApi.js';
import './KnowledgeMap.css';
const blank={title:'',description:'',domain:'general',sortOrder:0,status:'draft'};
export function KnowledgeAdmin({showToast}) {
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[id,setId]=useState(''),[form,setForm]=useState(blank),[edges,setEdges]=useState([]),[bindings,setBindings]=useState([]),[goals,setGoals]=useState([]),[goalTitle,setGoalTitle]=useState('');
 const request=useRef(0);
 const load=async()=>{const n=++request.current;try{const d=await getManagedKnowledgeMap();if(n===request.current){setData(d);setError('');}}catch(e){if(n===request.current)setError(e.message);}};
 useEffect(()=>{void load();return()=>{request.current++;};},[]);
 const act=async work=>{setBusy(true);try{await work();showToast('已保存');await load();}catch(e){showToast(e.message);}finally{setBusy(false);}};
 const select=n=>{setId(n?.id??'');setForm(n?{title:n.title,description:n.description,domain:n.domain,sortOrder:n.sortOrder,status:n.status}:blank);setEdges(data.edges.filter(e=>e.fromNodeId===n?.id).map(e=>({toNodeId:e.toNodeId,relation:e.relation})));setBindings(data.bindings.filter(b=>b.nodeId===n?.id).map(({targetType,targetId})=>({targetType,targetId})));setGoals(data.nodeGoals.filter(g=>g.nodeId===n?.id).map(g=>g.goalId));};
 if(error)return <section className="knowledge-live"><p role="alert">{error}</p><button onClick={load}>重新加载</button></section>;
 if(!data)return <section className="knowledge-live" aria-busy="true">正在加载知识图谱管理…</section>;
 const toggle=(setter,key,item)=>setter(list=>list.some(v=>key(v)===key(item))?list.filter(v=>key(v)!==key(item)):[...list,item]);
 return <section className="knowledge-live"><header><div><h1>知识图谱管理</h1><p>维护知识点、前置关系、学习资源和能力目标。发布后学生可查看。</p></div><button disabled={busy} onClick={()=>act(syncKnowledgeLabels)}>同步已发布内容标签</button></header><div className="knowledge-live__layout"><aside><button onClick={()=>select(null)}>新建知识点</button>{data.nodes.map(n=><button key={n.id} onClick={()=>select(n)}>{n.title} · {({draft:'草稿',published:'已发布',archived:'已归档'})[n.status]}</button>)}</aside><div><form onSubmit={e=>{e.preventDefault();void act(async()=>{const node=id?await updateKnowledgeNode(id,form):await createKnowledgeNode(form);setId(node.id);});}}><h2>{id?'编辑知识点':'新建知识点'}</h2><label>名称<input required value={form.title} maxLength={120} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>说明<textarea value={form.description} maxLength={2000} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>知识方向<input required value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}/></label><label>排序<input type="number" min="0" max="100000" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><label>状态<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">草稿</option><option value="published">发布</option><option value="archived">归档</option></select></label><button disabled={busy}>保存知识点</button></form>
 {id&&<form onSubmit={e=>{e.preventDefault();void act(()=>saveKnowledgeLinks(id,{edges,bindings,goalIds:goals}));}}><h3>关联配置</h3><fieldset><legend>后续知识点与相关知识</legend><p>前置关系方向：当前知识点 → 所选后续知识点。后台会拒绝循环。</p>{data.nodes.filter(n=>n.id!==id).map(n=><label key={n.id}>{n.title}<select aria-label={n.title+'的关系'} value={edges.find(e=>e.toNodeId===n.id)?.relation??''} onChange={e=>setEdges(list=>[...list.filter(v=>v.toNodeId!==n.id),...(e.target.value?[{toNodeId:n.id,relation:e.target.value}]:[])])}><option value="">不关联</option><option value="prerequisite">作为其前置知识</option><option value="related">相关知识</option></select></label>)}</fieldset><fieldset><legend>资源绑定</legend>{data.catalog.map(c=><label key={c.targetType+c.targetId}><input type="checkbox" checked={bindings.some(b=>b.targetType===c.targetType&&b.targetId===c.targetId)} onChange={()=>toggle(setBindings,v=>v.targetType+':'+v.targetId,{targetType:c.targetType,targetId:c.targetId})}/>{c.title} · {({course:'课程',lesson:'课时',workflow:'工作流',tool:'工具'})[c.targetType]} · {({draft:'草稿',published:'已发布',archived:'已归档',pending_review:'待审核',rejected:'已驳回'})[c.status]??c.status}</label>)}</fieldset><fieldset><legend>能力目标</legend>{data.goals.map(g=><label key={g.id}><input type="checkbox" checked={goals.includes(g.id)} onChange={()=>setGoals(list=>list.includes(g.id)?list.filter(x=>x!==g.id):[...list,g.id])}/>{g.title}</label>)}</fieldset><button disabled={busy}>保存关系与资源</button></form>}</div></div>
 <form onSubmit={e=>{e.preventDefault();void act(async()=>{await createAbilityGoal({title:goalTitle,status:'draft'});setGoalTitle('');});}}><h3>能力目标管理</h3><label>新增目标<input required maxLength={120} value={goalTitle} onChange={e=>setGoalTitle(e.target.value)}/></label><button disabled={busy}>创建草稿目标</button></form>{data.goals.map(g=><article key={g.id}><strong>{g.title}</strong><label>状态<select disabled={busy} value={g.status} onChange={e=>act(()=>updateAbilityGoal(g.id,{status:e.target.value}))}><option value="draft">草稿</option><option value="published">已发布</option><option value="archived">归档</option></select></label></article>)}</section>;
}
