import { NotFoundException } from "@nestjs/common";
import { realpath } from "node:fs/promises";
import path from "node:path";

// Accept only legacy UUID keys or the exact owner/work prefix generated by uploads.
// A valid-looking key for another work must never resolve to that work's file.
export async function resolveWorkAssetPath(root: string, key: string, authorId: string, workId: string) {
  const filename = "[a-f0-9-]{36}-[a-f0-9-]{36}";
  const leaf = new RegExp(`^${filename}$`, "i");
  const prefix = `users/${authorId}/works/${workId}/`;
  if (!leaf.test(key) && !(key.startsWith(prefix) && leaf.test(key.slice(prefix.length)) &&
    [authorId, workId].every(id => /^[A-Za-z0-9_-]{1,160}$/.test(id)))) {
    throw new NotFoundException("资源存储记录无效");
  }
  try {
    const actualRoot = await realpath(root);
    const actualFile = await realpath(path.resolve(root, ...key.split("/")));
    const relative = path.relative(actualRoot, actualFile);
    if (!relative || relative.startsWith(`..${path.sep}`) || relative === ".." || path.isAbsolute(relative)) throw new Error("outside root");
    return actualFile;
  } catch { throw new NotFoundException("作品文件不存在或已不可用"); }
}
